{
 "title": "C-Chain Load",
 "description": "Collection of load testing dashboard set to C chain by default.",
 "tags": [
  "Avalanche",
  "Performance"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter" },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Load test metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Issued txs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "txs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(load_txs_issued)", "legendFormat": "Confirmed" }
   ]
  },
  {
   "title": "Confirmed txs",
   "type": "stat",
   "description": "Issued transactions which are confirmed and accepted in a block",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "txs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(load_txs_confirmed)", "legendFormat": "Confirmed" }
   ]
  },
  {
   "title": "Failed txs",
   "type": "stat",
   "description": "Issued transactions which are confirmed and accepted in a block",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "txs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(load_txs_failed)", "legendFormat": "Confirmed" }
   ]
  },
  {
   "title": "In flight txs",
   "type": "stat",
   "description": "Transactions issued but not yet confirmed or failed",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "txs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(load_txs_issued)-sum(load_txs_confirmed)-sum(load_txs_failed)",
     "legendFormat": "Confirmed"
    }
   ]
  }
 ]
}