{
 "title": "C-Chain",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "node", "label": "Node", "query": "label_values(node)" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Last Accepted Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avalanche_snowman_last_accepted_height{chain=\"C\", node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Verified MGas/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_block_gas_used_processed{chain=\"C\", node=~\"$node\"}[1m])) / 1000000",
     "legendFormat": "{{node}} MGas / s"
    }
   ]
  },
  {
   "title": "Block Processing %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_trie{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Content Validation %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_trie{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} State Init %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_trie{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Execution %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_trie{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} State Validation %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_account_hashes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_hashes{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_trie{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Trie Hashes %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_account_updates{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_updates{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_trie{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Trie Update %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_storage_reads{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_trie{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Trie Storage Read %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_snapshot_storage_reads{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_trie{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Snapshot Storage Read %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_account_reads{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_trie{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Trie Account Read %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_snapshot_account_reads{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_trie{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Snapshot Account Read %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_trie{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Write %"
    },
    {
     "expr": "(sum by (node) (rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]))) / (sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_trie{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Commit Total %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_block_validations_content{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_inits_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_executions{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_validations_state{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_trie{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_writes{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_evm_eth_chain_block_signature_recovery{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Signature Recovery %"
    }
   ]
  },
  {
   "title": "Commit Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Account Commit %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Storage Commit %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Snapshot Commit %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_account_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_storage_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_snapshot_commits{chain=\"C\", node=~\"$node\"}[1m])) + sum by (node) (rate(avalanche_evm_eth_chain_triedb_commits{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} TrieDB Commit %"
    }
   ]
  },
  {
   "title": "EVM Accepted TPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_txs_accepted{chain=\"C\", node=~\"$node\"}[1m]))",
     "legendFormat": "{{node}} EVM Accepted TPS"
    }
   ]
  },
  {
   "title": "Blocks Verified / S",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_block_inserts_count{chain=\"C\", node=~\"$node\"}[1m]))",
     "legendFormat": "{{node}} Blocks Verified / S"
    }
   ]
  },
  {
   "title": "Txs / Block",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (node) (rate(avalanche_evm_eth_chain_txs_processed{chain=\"C\", node=~\"$node\"}[1m])) / (sum by (node) (rate(avalanche_evm_eth_chain_block_inserts_count{chain=\"C\", node=~\"$node\"}[1m])) + 0.000001)",
     "legendFormat": "{{node}} Txs / Block"
    }
   ]
  },
  {
   "title": "Rejected Blocks in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(avalanche_snowman_blks_rejected_count{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[1m]))>0",
     "legendFormat": "Blocks {{node}}"
    }
   ]
  },
  {
   "title": "Accepted Blocks in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(avalanche_snowman_blks_accepted_count{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[1m]))>0",
     "legendFormat": "Blocks {{node}}"
    }
   ]
  },
  {
   "title": "Average Block Rejection Latency",
   "type": "timeseries",
   "description": "The average time between a block's issuance and rejection by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_snowman_blks_rejected_sum{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[5m]) / rate(avalanche_snowman_blks_rejected_count{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[5m])",
     "legendFormat": "Avg Rejection Latency {{node}}"
    }
   ]
  },
  {
   "title": "Average Block Acceptance Latency",
   "type": "timeseries",
   "description": "The average time between a block's issuance and acceptance by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_snowman_blks_accepted_sum{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[5m]) / rate(avalanche_snowman_blks_accepted_count{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[5m])",
     "legendFormat": "Avg Acceptance Latency {{node}}"
    }
   ]
  },
  {
   "title": "Incomplete Polls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_snowman_polls{chain=\"C\", node=~\"$node\"} > 0",
     "legendFormat": "Polls {{node}}"
    }
   ]
  },
  {
   "title": "Processing Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_snowman_blks_processing{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}>0",
     "legendFormat": "Blocks {{node}}"
    }
   ]
  },
  {
   "title": "Percentage of Successful Queries",
   "type": "timeseries",
   "description": "Percentage of queries for which we receive chits on time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "($A + 1) / ($A + $B + 1)", "type": "math" }
   ]
  },
  {
   "title": "Message Handling Time (Total)",
   "type": "timeseries",
   "description": "Measures how much of each second is being spent handling different kinds of messages on the C-Chain.\nThe value for chits, for example, is the number of seconds spent handling chits messages per second, over the last 30 seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_handler_message_handling_time{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[5m])",
     "legendFormat": "{{ op }} {{node}}"
    }
   ]
  },
  {
   "title": "Message Handling Time (per Message)",
   "type": "timeseries",
   "description": "Measures how long each kind of request on the C-Chain takes to handle.\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_handler_message_handling_time{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[5m])/rate(avalanche_handler_messages{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[5m])",
     "legendFormat": "{{ op }} {{node}}"
    }
   ]
  },
  {
   "title": "Unprocessed Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avalanche_handler_sync_unprocessed_msgs_count{chain=\"C\", node=~\"$node\"}",
     "legendFormat": "{{ op }} {{node}}"
    },
    {
     "expr": "avalanche_handler_async_unprocessed_msgs_count{chain=\"C\", node=~\"$node\"}",
     "legendFormat": "{{node}} {{ op }}"
    }
   ]
  },
  {
   "title": "Incoming Messages Expired in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(avalanche_handler_expired{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[1m]) or 0 * up",
     "legendFormat": "{{ op }} {{node}}"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "timeseries",
   "description": "Measures how many of each kind of message are received per second on the C-Chain.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(avalanche_handler_messages{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[5m])",
     "legendFormat": "{{ op }} {{node}}"
    }
   ]
  },
  {
   "title": "AVAX Benched",
   "type": "timeseries",
   "description": "The total stake of validators currently \"benched\" due to poor query responsiveness. Queries to these validators will immediately timeout until they are removed from the \"bench.\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(avalanche_benchlist_benched_weight{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[15m]) / 10^9",
     "legendFormat": "AVAX Benched {{node}}"
    }
   ]
  },
  {
   "title": "Decided Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the decided block cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Block ID Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the cache where the key is the byte representation of the block, and the value is the block's ID",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Unverified Block Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the unverified block cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Missing Block Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the missing block cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Block Execution % (MeterVM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(avalanche_meterchainvm_parse_block_sum{chain=\"C\", node=~\"$node\"}[1m])) / sum by (node) (rate(avalanche_meterchainvm_parse_block_sum{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_meterchainvm_verify_sum{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_meterchainvm_accept_sum{chain=\"C\", node=~\"$node\"}[1m]))",
     "legendFormat": "{{node}} Parse %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_meterchainvm_verify_sum{chain=\"C\", node=~\"$node\"}[1m])) / sum by (node) (rate(avalanche_meterchainvm_parse_block_sum{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_meterchainvm_verify_sum{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_meterchainvm_accept_sum{chain=\"C\", node=~\"$node\"}[1m]))",
     "legendFormat": "{{node}} Verify %"
    },
    {
     "expr": "sum by (node) (rate(avalanche_meterchainvm_accept_sum{chain=\"C\", node=~\"$node\"}[1m])) / sum by (node) (rate(avalanche_meterchainvm_parse_block_sum{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_meterchainvm_verify_sum{chain=\"C\", node=~\"$node\"}[1m]) + rate(avalanche_meterchainvm_accept_sum{chain=\"C\", node=~\"$node\"}[1m]))",
     "legendFormat": "{{node}} Accept %"
    }
   ]
  },
  {
   "title": "Average Block Parse Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "sum(rate(avalanche_meterchainvm_parse_block_sum{chain=\"C\", node=~\"$node\"}[5m]) / 1000000) / sum(rate(avalanche_meterchainvm_parse_block_count{chain=\"C\", node=~\"$node\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Average Block Verify Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "sum(rate(avalanche_meterchainvm_verify_sum{chain=\"C\", node=~\"$node\"}[5m]) / 1000000) / sum(rate(avalanche_meterchainvm_verify_count{chain=\"C\", node=~\"$node\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Average Block Accept Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum(rate(avalanche_meterchainvm_accept_sum{chain=\"C\", node=~\"$node\"}[5m]) / 1000000) / sum(rate(avalanche_meterchainvm_accept_count{chain=\"C\", node=~\"$node\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}