{
 "title": "Database",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "node", "label": "Node", "query": "label_values(node)" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Database Read Rate",
   "type": "timeseries",
   "description": "Database read rate. Note that these reads may be from caches and not from disk.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(avalanche_meterdb_size{chain=\"all\", method=~\"has|get|iterator_next\"}[5m]))",
     "legendFormat": "Bytes Read {{node}}"
    }
   ]
  },
  {
   "title": "Database Write Rate",
   "type": "timeseries",
   "description": "Database write rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(avalanche_meterdb_size{chain=\"all\", method=~\"put|delete|batch_write\"}[5m]))",
     "legendFormat": "Bytes Written {{node}}"
    }
   ]
  },
  {
   "title": "Total Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second across all chains",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(avalanche_meterdb_calls{chain=\"all\", job=\"avalanchego\", node=~\"$node\"}[5m])",
     "legendFormat": "{{ method }} {{node}}"
    }
   ]
  },
  {
   "title": "Total Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_meterdb_duration{chain=\"all\", job=\"avalanchego\", node=~\"$node\"}[5m])/increase(avalanche_meterdb_calls{chain=\"all\", job=\"avalanchego\", node=~\"$node\"}[5m])",
     "legendFormat": "{{ method }} {{node}}"
    }
   ]
  },
  {
   "title": "X-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second on X-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(avalanche_meterdb_calls{chain=\"X\", job=\"avalanchego\", node=~\"$node\"}[5m])",
     "legendFormat": "{{ method }} {{node}}"
    }
   ]
  },
  {
   "title": "X-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on X-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_meterdb_duration{chain=\"X\", job=\"avalanchego\", node=~\"$node\"}[5m])/increase(avalanche_meterdb_calls{chain=\"X\", job=\"avalanchego\", node=~\"$node\"}[5m])",
     "legendFormat": "{{ method }} {{node}}"
    }
   ]
  },
  {
   "title": "P-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second on P-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(avalanche_meterdb_calls{chain=\"P\", job=\"avalanchego\", node=~\"$node\"}[5m])",
     "legendFormat": "{{ method }} {{node}}"
    }
   ]
  },
  {
   "title": "P-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on P-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_meterdb_duration{chain=\"P\", job=\"avalanchego\", node=~\"$node\"}[5m])/increase(avalanche_meterdb_calls{chain=\"P\", job=\"avalanchego\", node=~\"$node\"}[5m])",
     "legendFormat": "{{ method }} {{node}}"
    }
   ]
  },
  {
   "title": "C-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second across all chains",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(avalanche_meterdb_calls{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[5m])",
     "legendFormat": "{{ method }} {{node}}"
    }
   ]
  },
  {
   "title": "C-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on C-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_meterdb_duration{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[5m])/increase(avalanche_meterdb_calls{chain=\"C\", job=\"avalanchego\", node=~\"$node\"}[5m])",
     "legendFormat": "{{ method }} {{node}}"
    }
   ]
  }
 ]
}