{
 "title": "Machine Metrics",
 "description": "CPU, disk, memory, etc.",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "node", "label": "Node", "query": "label_values(node)" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"avalanchego-machine\", node=~\"$node\", mode=\"idle\"}[1m])) by (instance)) * 100",
     "legendFormat": "{{node}} CPU"
    }
   ]
  },
  {
   "title": "Machine Network I/O",
   "type": "timeseries",
   "description": "Include I/O from applications other than AvalancheGo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[5m])",
     "legendFormat": "{{node}} Receive {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[5m])",
     "legendFormat": "{{node}} Transmit {{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "Includes I/O from applications other than AvalancheGo",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[5m])",
     "legendFormat": "{{node}} Read {{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[5m])",
     "legendFormat": "{{node}} Write {{device}}"
    }
   ]
  },
  {
   "title": "Memory Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes{job=~\"avalanchego-machine\", node=~\"$node\"} - node_memory_MemFree_bytes{job=~\"avalanchego-machine\", node=~\"$node\"} - node_memory_Buffers_bytes{job=~\"avalanchego-machine\", node=~\"$node\"} - node_memory_Cached_bytes{job=~\"avalanchego-machine\", node=~\"$node\"}) / node_memory_MemTotal_bytes{job=~\"avalanchego-machine\", node=~\"$node\"}",
     "legendFormat": "{{node}} Memory"
    }
   ]
  },
  {
   "title": "Disk Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(((node_filesystem_size_bytes{job=~\"avalanchego-machine\", node=~\"$node\", fstype=~\"ext4|vfat\"} - node_filesystem_free_bytes{job=~\"avalanchego-machine\", node=~\"$node\", fstype=~\"ext4|vfat\"}) / node_filesystem_size_bytes{job=~\"avalanchego-machine\", node=~\"$node\", fstype=~\"ext4|vfat\"}) * 100) by (instance)",
     "legendFormat": "{{node}} Disk"
    }
   ]
  },
  {
   "title": "Number of Go goroutines",
   "type": "timeseries",
   "description": "Number of parallel execution threads in the client runtime",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avalanche_process_go_goroutines{job=~\"avalanchego\", node=~\"$node\"}",
     "legendFormat": "{{node}} goroutines"
    }
   ]
  }
 ]
}